### ISSUE TITLE
版本1.20.1，模组版本Beta 0.0.17

### ISSUE THREAD

**Issue by MFRarDer** [catmoon233/ExModifier#6]
问题描述：如果饰品是由数据包驱动的，词条订不上去。
<img width="284" alt="image" src="https://github.com/user-attachments/assets/7c961bfc-b304-4d8b-abc6-164766e4b417">
[这个饰品是由（泰拉饰品Terra Curio）添加的饰品，当手持物品时可以正常的将词条订上去。]
<img width="482" alt="image" src="https://github.com/user-attachments/assets/cbef04c0-84ab-425c-a986-d00b522bb117">
[KubeJS给的数据是这样]
<img width="259" alt="image" src="https://github.com/user-attachments/assets/a3a65a42-7455-4e60-9991-c2a1be7d103b">
[这个饰品是由（KubeJS）添加的物品，用数据包驱动的为这个物品加了Tag，当手持物品时词条并不能正常订上去。]
<img width="311" alt="image" src="https://github.com/user-attachments/assets/24a9fe28-f2fa-4863-a267-caa0f7be6f11">
[但我发现当把它放到饰品栏那里的时候，他可以正常显示一个描述？（我不知道该怎么描述），但是并不会有效果。]
<img width="482" alt="image" src="https://github.com/user-attachments/assets/8eea64f2-0b82-406d-99ea-39aae25d0a4b">
[KubeJS给的数据是这样]
<img width="453" alt="image" src="https://github.com/user-attachments/assets/ebba4f1c-e64e-4566-8ae7-fb2483dec9ab">
[然后可以正常的把它放到锻造台里面（材料我自己改了一下）]
<img width="275" alt="image" src="https://github.com/user-attachments/assets/77abef83-7b79-4872-9071-1f05141fcdc2">
[从锻造台里面拿出来之后，会什么都没有了，也不能再次重铸（拿到背包里面就是这样）]
<img width="265" alt="image" src="https://github.com/user-attachments/assets/06658ec7-9139-485e-abee-5f4639ca9053">
[并且它放到饰品栏里面也不会再出现那个描述]
<img width="374" alt="image" src="https://github.com/user-attachments/assets/04f31f3c-e8c8-4452-9205-91051eed524c">
[它也不能再次重铸了]
<img width="482" alt="image" src="https://github.com/user-attachments/assets/8c296e45-e06d-4fad-a40c-55cecf2faee2">
[KubeJS给的数据是这样 ]

**Comment by MFRarDer** [comment]
也许这个问题和[GitHUB链接](https://github.com/wisp-forest/accessories/issues/100)这个模组这个问题有相似的问题，我不知道是否正确但是应该可以参考一下。

**Comment by catmoon233** [comment]
最新版已修复
